[package]
name = "raytracer"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.20"
pollster = "0.3.0"
wgpu = "0.18.0"
winit = "0.28"
env_logger = "0.10.1"
bytemuck = { version = "1.14.0", features = ["derive"] }
cgmath = "0.18.0"
